# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Matthew Palmer

# Short description (goes below the title; it will also be used in the RSS feed)
description: Web and iOS developer from Australia. @_matthewpalmer.

# Your name, as you want it to appear underneath each post and in the footer
author: Matthew Palmer

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

safe: true

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
# baseurl: /blog

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.matthewpalmer.net


# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true
server: true
pygments: true
permalink: /blog/:title
paginate: 10
markdown: rdiscount
